name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_APP_ENV: dev
      NEXT_PUBLIC_BALANCER_API_URL: ${{ secrets.NEXT_PUBLIC_BALANCER_API_URL }}
      NEXT_PUBLIC_WALLET_CONNECT_ID: ${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_ID }}
      NEXT_PRIVATE_DRPC_KEY: ${{ secrets.NEXT_PRIVATE_DRPC_KEY }}
      NEXT_PUBLIC_MAGPIE_TOKENS_API: ${{ secrets.NEXT_PUBLIC_MAGPIE_TOKENS_API }}
      NEXT_PUBLIC_GRAPH_API_URL: ${{ secrets.NEXT_PUBLIC_GRAPH_API_URL }}
      NEXT_PUBLIC_GRAPH_API_KEY: ${{ secrets.NEXT_PUBLIC_GRAPH_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_APP_ENV=dev" >> .env
          echo "NEXT_PUBLIC_BALANCER_API_URL=${{ secrets.NEXT_PUBLIC_BALANCER_API_URL }}" >> .env
          echo "NEXT_PUBLIC_WALLET_CONNECT_ID=${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_ID }}" >> .env
          echo "NEXT_PRIVATE_DRPC_KEY=${{ secrets.NEXT_PRIVATE_DRPC_KEY }}" >> .env
          echo "NEXT_PUBLIC_MAGPIE_TOKENS_API=${{ secrets.NEXT_PUBLIC_MAGPIE_TOKENS_API }}" >> .env
          echo "NEXT_PUBLIC_GRAPH_API_URL=${{ secrets.NEXT_PUBLIC_GRAPH_API_URL }}" >> .env
          echo "NEXT_PUBLIC_GRAPH_API_KEY=${{ secrets.NEXT_PUBLIC_GRAPH_API_KEY }}" >> .env
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
